aws_region            = "us-west-2"
project               = "thaqhiri"
environment           = "staging"
vpc_cidr              = "10.1.0.0/16"
public_subnet_cidrs   = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet_cidrs  = ["10.1.10.0/24", "10.1.20.0/24"]
availability_zones    = ["us-west-2a", "us-west-2b"]
ssh_allowed_cidrs     = ["0.0.0.0/0"]
ec2_instance_type     = "t3.micro"
rds_instance_class    = "db.t3.micro"
rds_allocated_storage = 20
db_name               = "thaqhiri"
bucket_suffix         = "023894313590"
github_org            = "ProyectoIntegradorCOS"
github_repos          = ["proyint-backend", "proyint-infrastructure"]
